color: green
description: null
fieldLayouts:
  6f464c8e-af00-4744-ad23-845636ffd5e3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-11T08:26:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'The green title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f0f1b711-a4d3-4596-a410-b4dd48eda27f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 530337e9-649d-4670-86c9-c28007f7bcc1
        userCondition: null
handle: green
hasTitleField: true
icon: arrows-maximize
name: Green
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
