color: null
description: null
fieldLayouts:
  0001fe3d-3f4d-443c-8cc5-fd88aaa882b7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T08:08:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a47cecba-c95c-4cfb-b540-0e8ef4058667 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d74a011-adc2-4ea6-855a-3f55e7837b3e
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-08T08:08:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 41d02504-2503-4e44-902d-0737b4f8e313 # Heading level
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b14a1151-d5f7-4ee1-b3c2-a5fa4e9e70ae
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 1c7a814a-9a74-4d8f-ad40-c1e1f50f5366
        userCondition: null
handle: heading
hasTitleField: false
icon: heading
name: Heading
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
