color: null
description: null
fieldLayouts:
  4714d2d5-c039-4c94-9e10-ec61669ffadf:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:3a5d384d-5760-46d4-b18c-573feec2c1c8'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T07:30:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0ffb44ee-5128-454b-9a89-eb8f3203493c # Internal Link
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a5d384d-5760-46d4-b18c-573feec2c1c8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 64e68399-da4d-4526-beee-77928496dba3
        userCondition: null
handle: internalLink
hasTitleField: false
icon: memo
name: 'Internal Link'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
