color: null
description: null
fieldLayouts:
  e0c6f200-8887-4709-969b-911b80e6191a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T08:21:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9f7fa161-dafa-44b5-a4ff-93743b0acab8 # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31c674a6-ebf6-4814-a230-9e0b41272fb1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f5906da-fe2d-4df6-84f3-3baf9761b3f7
        userCondition: null
handle: links
hasTitleField: false
icon: null
name: Links
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
