color: null
description: null
fieldLayouts:
  a0fa8f5f-7d12-419f-bbf6-7d575c98f259:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-08T07:09:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e9d592ad-603d-47fb-9544-daa5d44eb3e0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T07:20:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cd83beee-0ccd-43f2-a740-84573f2ae81a # Repeatable Field Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e000c944-a20f-4e5f-8075-125eb34f0df9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T07:30:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 139946b5-d020-4977-9d87-87e9c8f8e63c # Repeatable Field Matrix - Multiple types
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3883ab68-7aca-421e-9f9b-f3ce992fccf0
            userCondition: null
            warning: null
            width: 100
        name: 'Repeatable Fields'
        uid: e1e14d8c-dabc-44f3-98e8-4acbe275411d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T07:43:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 63059daf-4263-4a58-8eac-33b26f6b49b7 # Attributed Relationship
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8203ef2c-4229-4253-992d-75030c105c17
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T07:46:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 850385b8-7f29-496e-9e5b-1b22d8eb46ed # Attributed Relationship - Cards view mode
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a710a699-d92d-4e1a-be67-be824b3b4714
            userCondition: null
            warning: null
            width: 100
        name: 'Attributed Relationships'
        uid: efa9be19-9512-4050-9efb-59dc8278a211
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T08:11:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 21dc7066-46d0-4e53-b141-08ba3d9d1823 # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a9e103a-4a15-4f2c-8c57-fffe4dbcaab6
            userCondition: null
            warning: null
            width: 100
        name: 'Content Builder'
        uid: b51a2ecf-1b07-49fb-9c95-e44eb1f57e5e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T12:53:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2b1eb865-cdd6-4405-9183-438460f762c1 # Vita - Inline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f13ed4b0-495f-444b-84c4-a552d80369d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T13:23:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6f7de782-9105-4f60-8eef-b18e9b0e1993 # Vita - Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee9494e8-f218-40b5-994c-996773f66e45
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T13:30:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f8c4b31b-7c1f-4c15-804e-24ee7b04f4ac # Vita - Element Index
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 735b60c7-9860-4c6f-b06a-68e449dfbec2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T08:02:48+00:00'
            dismissible: false
            elementCondition: null
            style: warning
            tip: 'Changes to nested elements in element index mode are published immediately and are not part of the owning elements life cycle!'
            type: craft\fieldlayoutelements\Tip
            uid: e648a752-a973-48ac-9044-57909973873f
            userCondition: null
        name: 'Structured Data'
        uid: b1328e90-275a-4969-a17c-4b30e078009e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T14:06:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 050ebc1a-8578-433d-b6a4-6c31eb1bc8e0 # Two Columns
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1fcf254-28a7-4b88-b522-87e4173b75ef
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: f1e494f3-84d0-4ea2-b81f-c551872017ce
        userCondition: null
handle: matrixKitchensink
hasTitleField: true
icon: block-brick
name: 'Matrix Kitchensink'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
