color: null
description: null
fieldLayouts:
  f6569f7a-7ad5-41c9-937e-e5f8f7667da1:
    cardThumbAlignment: end
    cardView:
      - 'generatedField:91c655e5-a50e-4b09-aaa4-afc6aa5c05ab'
    generatedFields:
      -
        handle: videoData
        name: 'Video Data'
        template: 'Runtime: {videoRuntime} min., Dimensions: {videoWidth}x{videoHeight}px'
        uid: 91c655e5-a50e-4b09-aaa4-afc6aa5c05ab
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-09T08:26:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eb80f7ec-4833-4c10-85fc-d021f90dff4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-09T08:31:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b7665acd-fd6e-4156-938a-fd03b9de5f3d # JSON Field
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c34215c-529b-4c34-85ff-0bff82e41716
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-09T08:31:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 171725ac-6000-448e-ae63-0ff45e94a624 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81da5258-91d3-4def-b53a-0cb106733731
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-09T08:34:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c773d1-3deb-49a9-a925-c4774db19691 # Addresses
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d624b7a-5243-422d-a080-aed6057209d8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-09T08:31:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 032f75df-ef9b-419e-93d5-6151414d82ac # Country
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48039792-a2dd-4987-9689-c1491a7bdbd4
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-09T09:38:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ecf74218-9d59-4658-9b9e-1de8c69884e4 # Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a8087dc-9174-4f22-b545-2f11cdb2538c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-09T08:43:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 32af2e7c-ddf1-4c8d-9a82-d014f3a79ec7 # Users
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d91ca78-c0c4-4eb9-bce2-7dd8f3c78080
            userCondition: null
            warning: null
            width: 50
        name: 'Special fields'
        uid: 6967142d-4d6c-4447-8271-2e6dc5e88307
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-09T09:00:22+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Group reusable fields'
            type: craft\fieldlayoutelements\Tip
            uid: 44fdb5f7-4868-4017-993b-05e3dc1bb5b5
            userCondition: null
          -
            dateAdded: '2025-07-09T08:59:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 01323385-092b-4eb1-a8e0-8a1ca2819a15 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 699ba33d-9c93-4939-a13e-93c5880219e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-09T08:54:14+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Simulating columns layout with a content block field (with hidden label and view mode: Inline)'
            type: craft\fieldlayoutelements\Tip
            uid: 4e96241f-ab0b-48b5-9129-3745cea85b1d
            userCondition: null
          -
            dateAdded: '2025-07-09T08:50:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 33682359-2906-4f09-9b07-f8f2dc6e3282 # Multiple Images - List mode
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 885e8214-9c40-44e6-95cb-6d53f20c8926
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-09T08:50:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 91a71db5-2a9e-461c-ab92-fb650a4a960f # Properties
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c2cc11a-1ba4-47fb-99b5-87d2d86912aa
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-09T09:03:17+00:00'
            dismissible: false
            elementCondition: null
            style: warning
            tip: "A serious limitation: (with todays knowledge): Subfields of a content block field can't be used out of the box for filtering/ordering in element queries."
            type: craft\fieldlayoutelements\Tip
            uid: e4717434-cda9-49d6-bfe3-4eea6ce1be71
            userCondition: null
        name: 'Content Block'
        uid: ff48413a-0f80-43ae-a900-6c16c363eebf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-11T07:43:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7fa57b99-5a49-4f9c-861a-718bdf911ebd # Show CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1423984f-8ff4-4042-97e7-d9584c1f4aee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-11T07:43:57+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 7fa57b99-5a49-4f9c-861a-718bdf911ebd # Show CTA
                  layoutElementUid: 1423984f-8ff4-4042-97e7-d9584c1f4aee
                  uid: f03a9f14-ae9c-43fb-a8f1-98660c0fa14c
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: ec62ed85-ce37-48ad-9e54-db7f2cf167f6 # Plaintext Multi Lines
            handle: ctaText
            includeInCards: false
            instructions: ' '
            label: 'CTA Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 468d3e69-65e2-47b3-bbe2-e503f219762c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-11T07:45:37+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 7fa57b99-5a49-4f9c-861a-718bdf911ebd # Show CTA
                  layoutElementUid: 1423984f-8ff4-4042-97e7-d9584c1f4aee
                  uid: 3dc58e33-00dd-417b-b328-e46982dad897
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 0ffb44ee-5128-454b-9a89-eb8f3203493c # Internal Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf91275f-e159-45e1-a904-fccaa697bc90
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-11T07:49:34+00:00'
            dismissible: false
            elementCondition: null
            style: warning
            tip: 'Hidden fields may still have content, so check the condition in your templates.'
            type: craft\fieldlayoutelements\Tip
            uid: da315837-9537-4ff3-83fa-6e78ae902bfa
            userCondition: null
          -
            dateAdded: '2025-07-11T08:01:23+00:00'
            elementCondition: null
            heading: 'User Conditions'
            type: craft\fieldlayoutelements\Heading
            uid: ba2959b5-ebdc-4d48-b914-306873783acf
            userCondition: null
          -
            content: "There are no additional users in a Craft SOLO project, so play with the 'Simulate restricted permissions' toggle in your user profile to see the effect."
            dateAdded: '2025-07-11T08:01:23+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 8455c672-76a1-451d-900c-1ef84ed3f637
            userCondition: null
            width: 100
          -
            dateAdded: '2025-07-11T08:01:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e73d4b9a-308e-447b-907f-e29ba99f8df7 # Plaintext Single Line
            handle: invisibleText
            includeInCards: false
            instructions: null
            label: 'Invisible for restricted users'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0697c203-28c0-446c-b1b3-a2e2d49584fa
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 5d1808fd-43f7-4070-b188-ba843b523598 # Simulate restricted permissions
                  layoutElementUid: 5483bab2-ce9b-444e-bd59-81a51f12f63a
                  uid: f2d42272-6ae7-4f7a-a241-74842be779c1
                  value: false
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 100
          -
            dateAdded: '2025-07-11T08:07:12+00:00'
            editCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 5d1808fd-43f7-4070-b188-ba843b523598 # Simulate restricted permissions
                  layoutElementUid: 5483bab2-ce9b-444e-bd59-81a51f12f63a
                  uid: 273d059d-1835-423f-927a-e07a430a0edd
                  value: false
              elementType: craft\elements\User
              fieldContext: global
            elementCondition: null
            fieldUid: e73d4b9a-308e-447b-907f-e29ba99f8df7 # Plaintext Single Line
            handle: notEditableText
            includeInCards: false
            instructions: null
            label: 'Not editable for restricted users'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32010df5-edf4-4b69-addc-9a9537b30aba
            userCondition: null
            warning: null
            width: 100
        name: Conditionals
        uid: c2e1083b-e261-4d60-9ef3-c2f8cf21d427
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-11T08:37:03+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Enhance entry types with colors and tabs.'
            type: craft\fieldlayoutelements\Tip
            uid: e8cb9c1f-3e23-42c7-acbd-8a1d7370e361
            userCondition: null
          -
            dateAdded: '2025-07-11T08:29:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c9506648-19ce-40d1-bdcc-b8ece806360e # Colored Entry Types - Inline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2c720a0-9b7d-4c6e-ae77-0711ee05a3fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-11T08:30:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1469256e-f1b5-4588-b090-006be6898744 # Colored Entry Types - Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f16a636-3978-47b4-a07c-6aaa0dd11f39
            userCondition: null
            warning: null
            width: 100
        name: Colors/Tabs
        uid: 6c72306e-9104-4602-a783-eb80f095e8df
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            content: "Generated field values are stored on every save, using an object twig template, in this case:\r\n\r\n`Runtime: {videoRuntime} min., Dimensions: {videoWidth}x{videoHeight}px`\r\n\r\nCan be displayed in edit form via a template UI element."
            dateAdded: '2025-07-11T09:13:01+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: bc867403-3fb2-4262-a1f5-fb855a643554
            userCondition: null
            width: 100
          -
            dateAdded: '2025-07-11T08:53:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e73d4b9a-308e-447b-907f-e29ba99f8df7 # Plaintext Single Line
            handle: videoRuntime
            includeInCards: false
            instructions: 'Format 1:30'
            label: 'Video Runtime'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d3f8b72-ae59-4f03-ba38-8e81373d9c6a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-11T08:53:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f5eff8f-7256-4dee-b7e2-dc8702278055 # Integer, min 0
            handle: videoWidth
            includeInCards: false
            instructions: 'in px'
            label: 'Video Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78b4ff5a-cfcf-45e0-b79a-f5e64ddd0b12
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-11T08:53:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f5eff8f-7256-4dee-b7e2-dc8702278055 # Integer, min 0
            handle: videoHeight
            includeInCards: false
            instructions: 'in px'
            label: 'Video Height'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83efde55-3140-42bd-b4c8-c2ad0f2923d4
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-11T08:56:14+00:00'
            elementCondition: null
            template: _cp/video-data.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 97675a53-476e-41cb-94a6-9e05d19c4a6c
            userCondition: null
            width: 100
          -
            dateAdded: '2025-07-11T09:14:40+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Use a generated field for a more user friendly card attribute.'
            type: craft\fieldlayoutelements\Tip
            uid: 534bc9e5-fa6f-49f3-84bc-9fb4e6904210
            userCondition: null
        name: 'Generated Fields'
        uid: 81a10d98-67ea-46b0-97bd-30480f8b2d75
        userCondition: null
handle: specialKitchensink
hasTitleField: true
icon: sparkles
name: 'Special Kitchensink'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
