columnSuffix: null
handle: attributedRelationship
instructions: 'Use matrix to allow adding attributes to a relationship'
name: 'Attributed Relationship'
searchable: false
settings:
  createButtonLabel: 'Add team member'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - b8580d7f-b47e-4f33-a91e-0f7bd588aa5d # Team Member
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
