columnSuffix: null
handle: color
instructions: 'Color picker only'
name: Color
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
