columnSuffix: null
handle: headingLevel
instructions: null
name: 'Heading level'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - H2
        -
          - value
          - h2
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - h3
        -
          - value
          - h3
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
