columnSuffix: null
handle: imageRestrictedToSingleLocation
instructions: "Stored in folder 'defaultlocation'\r\nCan be configured so that subfolders are allowed."
name: 'Image restricted to single location'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:faea02b7-cc0c-468b-8abe-45a289623532' # Images
  defaultUploadLocationSubpath: defaultlocation
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:faea02b7-cc0c-468b-8abe-45a289623532' # Images
  restrictedLocationSubpath: defaultlocation
  selectionLabel: 'Select an image'
  showCardsInGrid: true
  showSearchInput: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:faea02b7-cc0c-468b-8abe-45a289623532' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
