columnSuffix: null
handle: internalLink
instructions: null
name: 'Internal Link'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
  types:
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
