columnSuffix: null
handle: multipleEntriesSingleSource
instructions: 'Can have a search input and allows creation of new entries'
name: 'Multiple Entries - Single Source'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a post'
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:833fd9ba-8ec2-4720-a887-19088e4219fd' # Post
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
