columnSuffix: null
handle: multiSelectWithColorsIcons
instructions: null
name: 'Multi Select with colors/icons'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Bed
        -
          - value
          - bed
        -
          - icon
          - bed
        -
          - color
          - '#d71d1d'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Home
        -
          - value
          - home
        -
          - icon
          - caravan
        -
          - color
          - '#3c9f50'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Vacation
        -
          - value
          - vacation
        -
          - icon
          - island-tropical
        -
          - color
          - '#2952a3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Work
        -
          - value
          - work
        -
          - icon
          - person-digging
        -
          - color
          - '#5bd7cf'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\MultiSelect
