columnSuffix: null
handle: radio
instructions: null
name: Radio
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - North
        -
          - value
          - north
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - East
        -
          - value
          - east
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - South
        -
          - value
          - south
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - West
        -
          - value
          - west
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
