columnSuffix: null
handle: repeatingField
instructions: 'A table field can be used to make simple fields repeatable.'
name: 'Repeating Field'
searchable: false
settings:
  addRowLabel: 'Add a link'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Link
            -
              - handle
              - link
            -
              - width
              - ''
            -
              - type
              - url
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
