columnSuffix: null
handle: repeatableFieldMatrixMultipleTypes
instructions: "Mix different field types\r\nUse cards view mode"
name: 'Repeatable Field Matrix - Multiple types'
searchable: false
settings:
  createButtonLabel: 'New link'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 14fc9a06-af11-456a-acbd-e5de907e1d01 # Link
        -
          - name
          - 'External Link'
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 552d10fc-aac7-4148-8048-307b75dd671c # Internal Link
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
