columnSuffix: null
handle: simpleDatetimeWithTimezone
instructions: null
name: 'DateTime with timezone'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: true
  showTimeZone: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
