dateModified: 1752310234
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: Kitchensinks
      key: 'heading:3e3ebe90-6313-4bf9-b937-4426f6be39f5'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:f0dbae69-3acc-4e51-a1fd-f77049dd87f4' # Content Kitchen Sink
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:557a3d5f-648b-48e4-90f8-472a74643a51' # Relations Kitchen Sink
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:4e85e1ba-84c6-4fb5-b423-f1e61e66a867' # Matrix Kitchen Sink
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:1a51f395-7e68-48ec-8749-228aba9ce571' # Rich Text Kitchen Sink
      type: native
    -
      key: 'section:442601c9-e18e-45d9-a49f-2e4d0c01a09d' # Special Kitchen Sink
      type: native
    -
      heading: 'Dummy content'
      key: 'heading:c84ba410-47de-43f3-ae7d-0d0d5e809930'
      type: heading
    -
      key: 'section:833fd9ba-8ec2-4720-a887-19088e4219fd' # Post
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:14846542-ed30-4f9a-9934-c51436d1dfc5' # Person
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
email:
  fromEmail: admin@example.com
  fromName: 'Craft CMS'
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@webroot/files'
    type: craft\fs\Local
    url: '@weburl/files'
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: '@webroot/dist/transforms'
    type: craft\fs\Local
    url: '@weburl/dist/transforms'
meta:
  __names__:
    0e14f496-b3e2-46ec-ae4a-24425df0251a: 'Image with validation' # Image with validation
    0ffb44ee-5128-454b-9a89-eb8f3203493c: 'Internal Link' # Internal Link
    1a51f395-7e68-48ec-8749-228aba9ce571: 'Rich Text Kitchen Sink' # Rich Text Kitchen Sink
    1b3e74d7-c949-41bc-8a96-f3e43f364fd4: Date # Date
    1b4aa3b0-4e5d-47a4-8dba-ed4149c6d735: 'Date with min/max validation' # Date with min/max validation
    1b74bdc6-e3c9-4d27-a091-a7950e0f427a: 'One Image' # One Image
    2b1eb865-cdd6-4405-9183-438460f762c1: 'Vita - Inline' # Vita - Inline
    2df1efe9-9d3c-4557-8578-1e9b0812d630: Checkboxes # Checkboxes
    3ad15f79-3806-43c8-9cee-c7406bc904de: 'Special Kitchensink' # Special Kitchensink
    3ad99bc8-7f7b-42c9-a8a2-feef384a0fd7: Color # Color
    3bb9c2ce-e8f4-43f8-ab39-f0b01bc48cc0: Page # Page
    3f5eff8f-7256-4dee-b7e2-dc8702278055: 'Integer, min 0' # Integer, min 0
    4aa0a221-b893-4595-a902-10c3181afb2a: 'Color Palette' # Color Palette
    4e9cd5f3-fa8f-43bc-a002-25876f31802a: 'Column Widths' # Column Widths
    4e85e1ba-84c6-4fb5-b423-f1e61e66a867: 'Matrix Kitchen Sink' # Matrix Kitchen Sink
    5d1808fd-43f7-4070-b188-ba843b523598: 'Simulate restricted permissions' # Simulate restricted permissions
    6f7de782-9105-4f60-8eef-b18e9b0e1993: 'Vita - Cards' # Vita - Cards
    7a32e12b-2f36-4264-b6a7-9ad04666f138: 'Money with currency' # Money with currency
    7a732bd8-2e2a-48e8-b906-a50d5cadea6a: 'Content Kitchensink' # Content Kitchensink
    7c3c9635-e695-482d-a55b-f9102c718bef: 'Checkboxes with Color/Icons and custom values' # Checkboxes with Color/Icons and custom values
    7d7f13cf-6c66-4137-bd09-5830113ea59a: Lightswitch # Lightswitch
    7fa57b99-5a49-4f9c-861a-718bdf911ebd: 'Show CTA' # Show CTA
    8a2bd2fd-1bea-4875-a162-433f365b81eb: 'Role Image' # Role Image
    8b7688c3-bcda-497b-8cac-2c5c23ce6da2: 'Multiple Entries ' # Multiple Entries 
    8d34a7ed-9a72-4cd5-9d48-908d6170592d: 'Lightswitch with labels' # Lightswitch with labels
    8e615b76-f2a2-4fcf-a122-a3940b554ce8: 'Multi Select with colors/icons' # Multi Select with colors/icons
    9a8f08ff-8e03-452c-8da5-cb1d44fcf818: 'Right Column' # Right Column
    9ad1c8b7-bd7f-4683-8012-b21a1b19cd7e: 'Attributed Relationship -  Element index view mode' # Attributed Relationship -  Element index view mode
    9eb4f30a-4c3c-46c6-ba39-7fde854263cd: 'Button Group (Icons only)' # Button Group (Icons only)
    9f7fa161-dafa-44b5-a4ff-93743b0acab8: Links # Links
    11b3c55e-0b5b-44e8-a066-dd2d8d594722: 'Role Type' # Role Type
    14fc9a06-af11-456a-acbd-e5de907e1d01: Link # Link
    20f5adff-712d-4cdb-8736-cf7ba3b982bc: 'Radio with custom value' # Radio with custom value
    21dc7066-46d0-4e53-b141-08ba3d9d1823: 'Content Builder' # Content Builder
    26e23efd-dbc9-4c03-97bd-0da742e7674f: 'Relations Kitchensink' # Relations Kitchensink
    32af2e7c-ddf1-4c8d-9a82-d014f3a79ec7: Users # Users
    032f75df-ef9b-419e-93d5-6151414d82ac: Country # Country
    036f6fb3-bd0b-4d7d-a2a6-7beb59204c1a: Default # Default
    38b7f3c0-5362-4460-81cd-d145a313c2f1: 'URL Link Advanced' # URL Link Advanced
    40ecbe6a-e751-409c-94a5-bd88eaf5f9ed: Quote # Quote
    41d02504-2503-4e44-902d-0737b4f8e313: 'Heading level' # Heading level
    050ebc1a-8578-433d-b6a4-6c31eb1bc8e0: 'Two Columns' # Two Columns
    74b72af7-26e7-41d9-92ed-14d481e0a356: 'Single Entry - Single Source' # Single Entry - Single Source
    80e41654-a23a-4e72-ba55-bfc6a7c52180: Nested # Nested
    90c9ef57-71d3-461e-9080-5354e9d5a0f1: 'Multiple Images - Cards mode' # Multiple Images - Cards mode
    90e472bd-8372-475f-81f8-245d5a931e1a: 'Simple Rich Text' # Simple Rich Text
    91a71db5-2a9e-461c-ab92-fb650a4a960f: Properties # Properties
    93add84e-2f01-40d5-887e-20171d676d29: 'Static rows' # Static rows
    95d19936-609a-40a5-9333-be1db535f48e: Blue # Blue
    95dd478e-63d0-44fb-9bc2-bff8e4415e81: 'Multi Select' # Multi Select
    153fc909-74d8-4dc3-b1bb-b65cae06bd7c: 'SIngle Entry - Multiple Sources' # SIngle Entry - Multiple Sources
    226e9895-756d-404b-80d5-2c70bbd92ab6: 'Single Image' # Single Image
    234a5a4d-a3b9-4c09-a88a-726b37e01ee6: Radio # Radio
    388a6337-6d8a-4883-ad08-3b5fd4eec937: 'Left Column' # Left Column
    552d10fc-aac7-4148-8048-307b75dd671c: 'Internal Link' # Internal Link
    557a3d5f-648b-48e4-90f8-472a74643a51: 'Relations Kitchen Sink' # Relations Kitchen Sink
    643ea012-13b6-4182-990b-a0c939859e25: Red # Red
    708ad658-0530-4397-a406-ea48940e9e5c: 'Nested Rich Text' # Nested Rich Text
    769ae430-a215-42ce-90f2-68c156d46c10: Role # Role
    775fc597-d85b-42e5-9bfa-b211851371d6: 'Color Palette with Custom Color' # Color Palette with Custom Color
    833fd9ba-8ec2-4720-a887-19088e4219fd: Post # Post
    888fb6e1-fc89-4735-b1bd-e5bc44e8734b: 'DateTime with timezone' # DateTime with timezone
    948ccdf1-9d76-4e17-b7f0-e245a2bbba63: Links # Links
    982ea251-087b-4ea0-9044-91b3f2e56bf5: 'Plaintext limited bytes' # Plaintext limited bytes
    2178be4e-ae6f-485a-a241-dbffbd12733a: DateTime # DateTime
    2385b31e-523f-4c46-b312-fb94954e8e77: Image # Image
    8161d6f1-5414-416e-b5c4-dc4624625ec1: 'External Link' # External Link
    23101e1c-bf9a-4c7d-8cb5-4710a69d5261: 'Matrix Kitchensink' # Matrix Kitchensink
    47278c69-43c3-4a4c-a7a1-c46b7424f6d2: 'Multiple Entries - Multiple Sources' # Multiple Entries - Multiple Sources
    63059daf-4263-4a58-8eac-33b26f6b49b7: 'Attributed Relationship' # Attributed Relationship
    76666a59-39a6-4dc7-8933-2a83fb9c477e: Year # Year
    139946b5-d020-4977-9d87-87e9c8f8e63c: 'Repeatable Field Matrix - Multiple types' # Repeatable Field Matrix - Multiple types
    171725ac-6000-448e-ae63-0ff45e94a624: Icon # Icon
    283952e0-b0ca-4048-b122-0636fe8d83d5: Text # Text
    442601c9-e18e-45d9-a49f-2e4d0c01a09d: 'Special Kitchen Sink' # Special Kitchen Sink
    850385b8-7f29-496e-9e5b-1b22d8eb46ed: 'Attributed Relationship - Cards view mode' # Attributed Relationship - Cards view mode
    01323385-092b-4eb1-a8e0-8a1ca2819a15: SEO # SEO
    1469256e-f1b5-4588-b090-006be6898744: 'Colored Entry Types - Cards' # Colored Entry Types - Cards
    14846542-ed30-4f9a-9934-c51436d1dfc5: Person # Person
    33682359-2906-4f09-9b07-f8f2dc6e3282: 'Multiple Images - List mode' # Multiple Images - List mode
    a3a63e6d-ee11-4d78-a8a6-d561203645d1: 'Two Columns' # Two Columns
    a4f2973e-4934-46f7-af6d-b72af78abade: Primary # Primary
    a47cecba-c95c-4cfb-b540-0e8ef4058667: Heading # Heading
    ae6502f9-ab99-42e8-9025-3901f2fb5ffc: Home # Home
    af2f9236-ea82-48d0-a229-5741ac3b566e: 'Multiple Entries - Single Source' # Multiple Entries - Single Source
    b2c5dec0-185e-4a73-bb55-f08dfbdee880: 'Radio with Colors/Icons' # Radio with Colors/Icons
    b23e6e75-e5db-407a-846f-2e0291621ef1: Money # Money
    b5226b3f-be24-4e58-94ce-54b895a4f52b: Heading # Heading
    b7665acd-fd6e-4156-938a-fd03b9de5f3d: 'JSON Field' # JSON Field
    b8580d7f-b47e-4f33-a91e-0f7bd588aa5d: 'Team Member' # Team Member
    bdb8afff-03dd-4f92-a335-f3f410de4f7e: 'Multiple Images - Large Thumbnails' # Multiple Images - Large Thumbnails
    bf13c410-c10c-416d-9028-32180f334cec: 'Dropdown with Colors/Icons' # Dropdown with Colors/Icons
    c1c773d1-3deb-49a9-a925-c4774db19691: Addresses # Addresses
    c2cf4405-e2d1-40b0-9f04-3a827913690f: 'Plaintext limited characters' # Plaintext limited characters
    c74c7227-d078-4556-81a2-d990fcfc7307: 'Generic Link' # Generic Link
    c833dde2-9f09-4ad2-bdbb-c3d6bded0dd2: Time # Time
    c9506648-19ce-40d1-bdcc-b8ece806360e: 'Colored Entry Types - Inline' # Colored Entry Types - Inline
    cae6105d-13f3-4b8f-81b9-82d0986437f0: 'Plaintext Monospace' # Plaintext Monospace
    cd82ab5f-ddaf-4f06-bd20-280ad4a5b192: Table # Table
    cd83beee-0ccd-43f2-a740-84573f2ae81a: 'Repeatable Field Matrix' # Repeatable Field Matrix
    d99fe1e2-88e8-408d-a028-ca0c4db50316: 'Range Field' # Range Field
    da648d5f-18af-41e9-b835-adbc8b8195bb: Green # Green
    dba2e369-ab3b-463c-b1ce-854c36a34e66: 'Rich Text Kitchensink' # Rich Text Kitchensink
    de871e3a-39ad-4bd6-bca2-ab9917ed4767: Advanced # Advanced
    df31c4fb-c302-4ed2-a006-9d7b63d70cb2: 'Image restricted to single location - dynamic folder' # Image restricted to single location - dynamic folder
    e73d4b9a-308e-447b-907f-e29ba99f8df7: 'Plaintext Single Line' # Plaintext Single Line
    e779f2df-d90a-4f8a-b269-485ce02c5e21: 'Production Type' # Production Type
    ea3e5beb-ddf9-435e-b598-a3ae6f31f4cb: 'Decimal number, with prefix and suffix' # Decimal number, with prefix and suffix
    ec62ed85-ce37-48ad-9e54-db7f2cf167f6: 'Plaintext Multi Lines' # Plaintext Multi Lines
    ecf74218-9d59-4658-9b9e-1de8c69884e4: Email # Email
    edb618a6-8189-4fc0-81f0-0b730e698af1: Simple # Simple
    ee4f2d54-51bf-4853-b219-f2ad93d758d8: 'Image restricted to single location' # Image restricted to single location
    f0d7ce75-be54-4be3-b809-ae512616812c: 'Repeating Field' # Repeating Field
    f0dbae69-3acc-4e51-a1fd-f77049dd87f4: 'Content Kitchen Sink' # Content Kitchen Sink
    f8c4b31b-7c1f-4c15-804e-24ee7b04f4ac: 'Vita - Element Index' # Vita - Element Index
    f55a7ee9-7343-4f84-a51a-06a5a00f99cf: 'Advanced Rich Text' # Advanced Rich Text
    fa3c7ef9-23d0-45a9-88dd-c74e9aea679c: 'Button Group' # Button Group
    fa6e7e7e-ceaf-44eb-9cc9-938cf4d7f4d7: Person # Person
    faa22494-7395-4fdc-b0b6-4c1c4c1de010: Dropdown # Dropdown
    faea02b7-cc0c-468b-8abe-45a289623532: Images # Images
    fb3f5d93-1ca0-4a16-a2f6-25fd355de7f2: 'URL Link' # URL Link
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: 'Craft 5 Kitchensink'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: Europe/Berlin
