#!/bin/bash

cp setup/tailwind/package.json . &&
mkdir resources &&
mkdir resources/css &&
cp setup/tailwind/app.css resources/css/app.css &&
ddev npm install &&
ddev npm run build &&
echo Add this to your layout file: &&
echo '<link href="/dist/assets/app.css" rel="stylesheet">'
