#!/bin/bash

if [ -z $3 ]
then
    echo Usage: install project-name username password
    exit 1
fi

echo Installing project $1...
cp .env.example .env &&
ddev config --project-name=$1
ddev start &&
ddev composer install &&
ddev craft install --interactive=0 --username=$2 --password=$3 --email=admin@example.com &&
ddev describe &&
ddev launch



