defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3ad15f79-3806-43c8-9cee-c7406bc904de # Special Kitchensink
handle: specialKitchensink
maxAuthors: 1
name: 'Special Kitchen Sink'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - Dump
      -
        - urlFormat
        - 'dump?id={id}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a4f2973e-4934-46f7-af6d-b72af78abade: # Primary
    enabledByDefault: true
    hasUrls: true
    template: _entries/kitchensink/index.twig
    uriFormat: 'kitschensink/{slug}'
type: channel
